baseURL: "https://courses.inpyjama.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Learning Embedded Systems!"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "The in Pyjama team!"
  images:
    - "hero-image.png"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Raghevendra Circle, Bangalore 560016"

  contact:
    - "support@inpyja.com"
    - "business@inpyjama.com"

  copyright: "© 2024 Typobrahe Education LLP, Bangalore, India. All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About Us"
      url: "/about"
      weight: 2

    - name: "Community"
      url: "https://discord.com/servers/embedded-systems-party-inpyjama-1165531784293912576"
      weight: 3

    - name: "YouTube"
      url: "https://youtube.com/@inpyjama"
      weight: 4

    - name: "Courses"
      url: "https://learn.inpyjama.com/web/lite/store/65e18d38bf99dcd8b8119dcf"
      weight: 5

  buttons:
    - name: "Newsletter"
      url: "https://engineers.inpyjama.com/learn/embed-forms?formId=778"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "The Team"
      url: "/about"
      weight: 2

    - name: "Discord"
      url: "https://discord.com/servers/embedded-systems-party-inpyjama-1165531784293912576"
      weight: 3

    - name: "YouTube"
      url: "https://youtube.com/@inpyjama"
      weight: 4

    - name: "Newsletter"
      url: "https://engineers.inpyjama.com/learn/embed-forms?formId=778"
      weight: 5


taxonomies:
  series: "series"
  tags: "tags"
