baseURL: "https://courses.inpyjama.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: " Courses, in Pyjama!"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Courses by inpyjama!"
  images:
    - "hero-image.jpg"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "Raghevendra Circle, Bangalore 560016"

  contact:
    - "support@inpyja.com"
    - "business@inpyjama.com"

  copyright: "© 2024 Typobrahe Education LLP, Bangalore, India. All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "About Us"
      url: "/about"
      weight: 2

  buttons:
    - name: "Explore Courses"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Blog"
      url: "/#"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
